plugins:
  ldap_enabled:
    default: true
  ldap_user_create_mode:
    default: 'auto'
  ldap_lookup_users_by:
    default: 'email'
  ldap_hostname:
    default: 'forum.sonofrio.com'
  ldap_port:
    default: 389
  ldap_method:
    default: 'plain'
  ldap_base:
    default: 'dc=commonhelp,dc=it'
  ldap_uid:
    default: 'uid'
  ldap_bind_dn:
    default: 'cn=admin,dc=commonhelp,dc=it'
  ldap_password:
    default: ''
  ldap_filter:
    default: ''
